/* VM-tipset 2026 — publik data (inga kontaktuppgifter) */
const POOL_DATA = {
  meta: {
    title: "VM-tipset 2026",
    organizer: "Christer",
    swish: "070 693 99 70",
    cost_sek: 100,
    deadline: "2026-06-14T23:59:00+02:00",
    prize_split: { "1": 0.65, "2": 0.25, "3": 0.10 },
    show_countdown: false
  },
  matches: [
    { id: 1,  kickoff: "2026-06-15T01:00", home: "Elfenbenskusten", away: "Ecuador",      result: "1", score: "1-0" },
    { id: 2,  kickoff: "2026-06-15T04:00", home: "Sverige",         away: "Tunisien",     result: "1", score: "5-1" },
    { id: 3,  kickoff: "2026-06-15T21:00", home: "Belgien",         away: "Egypten",      result: "X", score: "1-1" },
    { id: 4,  kickoff: "2026-06-16T21:00", home: "Frankrike",       away: "Senegal",      result: "1", score: "3-1" },
    { id: 5,  kickoff: "2026-06-17T19:00", home: "Portugal",        away: "DR Kongo",     result: "X", score: "1-1" },
    { id: 6,  kickoff: "2026-06-17T22:00", home: "England",         away: "Kroatien",     result: "1", score: "4-2" },
    { id: 7,  kickoff: "2026-06-19T03:00", home: "Mexiko",          away: "Sydkorea",     result: "1", score: "1-0" },
    { id: 8,  kickoff: "2026-06-19T21:00", home: "USA",             away: "Australien",   result: "1", score: "2-0" },
    { id: 9,  kickoff: "2026-06-21T18:00", home: "Spanien",         away: "Saudiarabien", result: "1", score: "4-0" },
    { id: 10, kickoff: "2026-06-24T21:00", home: "Schweiz",         away: "Kanada",       result: "1", score: "2-1" },
    { id: 11, kickoff: "2026-06-25T00:00", home: "Skottland",       away: "Brasilien",    result: "2", score: "0-3" },
    { id: 12, kickoff: "2026-06-26T01:00", home: "Japan",           away: "Sverige",      result: "X", score: "1-1" },
    { id: 13, kickoff: "2026-06-28T04:00", home: "Algeriet",        away: "Österrike",    result: null, score: null }
  ],
  questions: [
    { id: "A", type: "text",    points: 2,              prompt: "Vem gör Sveriges första mål i VM?",                                                                                   correct:"Yasin Ayari"},
    { id: "B", type: "number",  points: 2, tolerance: 0, prompt: "Hur många gula kort blir det i Argentina - Österrike? (mån 22 juni 19:00)",                                           correct: "4" },
    { id: "C", type: "number",  points: 2, tolerance: 0, prompt: "Hur många mål gör Erling Haaland i VM? (mål under avgörande straffläggning räknas EJ)",                             correct: null },
    { id: "D", type: "twoteam", points: 4, scoring: "per_team_unordered", prompt: "Vilka två lag kommer 1:a och 2:a i grupp F?", options: ["Nederländerna","Japan","Sverige","Tunisien"], correct: ["Japan", "Nederländerna"] },
    { id: "E", type: "twoteam", points: 4, scoring: "per_team_unordered", prompt: "Vilka två lag kommer 1:a och 2:a i grupp I?", options: ["Frankrike","Irak","Norge","Senegal"],      correct: ["Frankrike", "Norge"] },
    { id: "F", type: "number",  points: 2, tolerance: 1, prompt: "Hur många av slutspelets 32 matcher går till förlängning eller straffläggning?<br>(+/- 1 match ger rätt)",             correct: null },
    { id: "G", type: "text",    points: 2,              prompt: "Vem vinner VM:s skytteliga? (delad skytteligavinst räknas som korrekt)",                                             correct: null },
    { id: "H", type: "text",    points: 2,              prompt: "Vilket land blir världsmästare?",                                                                                     correct: null }
  ],
  tiebreaker: {
    type: "number_closest",
    prompt: "Hur många straffar blir det under VM? (gäller ordinarie tid + förlängning, EJ straffläggningar)",
    correct: 10
  },
  participants: [
    {name:"Solveig Norin",contact:{phone:"",email:""},
     picks:{"1":["1"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1","X"],"9":["1"],"10":["X","2"],"11":["2"],"12":["X","2"],"13":["1","2"]},
     answers:{A:"Viktor Gyökeres",B:3,C:3,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:4,G:"Lamine Yamal",H:"Spanien"},tiebreaker:24,submitted:"26-06-05, 02:56"},
    {name:"Hans Erixon",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","2"],"8":["X"],"9":["1"],"10":["1","2"],"11":["2"],"12":["1","X"],"13":["1","X"]},
     answers:{A:"Sverige gör inga mål",B:3,C:5,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:9,G:"Erling Haaland",H:"Spanien"},tiebreaker:12,submitted:"26-06-05, 07:14"},
    {name:"Gabriel Popanicic",contact:{phone:"",email:""},
     picks:{"1":["1"],"2":["1","X"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1","2"],"9":["1"],"10":["1"],"11":["2"],"12":["X","2"],"13":["2"]},
     answers:{A:"Alexander Isak",B:3,C:5,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:8,G:"Ousmane Dembele",H:"Frankrike"},tiebreaker:38,submitted:"26-06-05, 09:39"},
    {name:"Felix Olsson",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1"],"7":["1","X"],"8":["1","X"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","X"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:4,C:3,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:7,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:28,submitted:"26-06-05, 10:31"},
    {name:"Love Olsson",contact:{phone:"",email:""},
     picks:{"1":["1"],"2":["X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1","X"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","X"],"13":["1","2"]},
     answers:{A:"Isak Hien",B:7,C:3,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:4,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:23,submitted:"26-06-05, 10:43"},
    {name:"Mats Erik Persson",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1"],"3":["1"],"4":["1","X"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1"],"11":["X","2"],"12":["1","X"],"13":["2"]},
     answers:{A:"Alexander Isak",B:3,C:4,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:14,G:"Erling Haaland",H:"Norge"},tiebreaker:22,submitted:"26-06-05, 11:00"},
    {name:"Johan Åkerlund",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1"],"7":["X","2"],"8":["1"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","X"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:5,C:4,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:8,G:"Harry Kane",H:"Spanien"},tiebreaker:42,submitted:"26-06-05, 13:14"},
    {name:"Tomas Flodin",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1","X"],"9":["1"],"10":["1"],"11":["X","2"],"12":["2"],"13":["1","2"]},
     answers:{A:"Viktor Gyökeres",B:4,C:7,D:["Nederländerna","Sverige"],E:["Frankrike","Senegal"],F:8,G:"Erling Haaland",H:"Brasilien"},tiebreaker:30,submitted:"26-06-05, 13:24"},
    {name:"Matz Ståby",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["X","2"],"3":["1"],"4":["1","X"],"5":["1"],"6":["1","2"],"7":["1"],"8":["1"],"9":["1"],"10":["1"],"11":["X","2"],"12":["1"],"13":["X","2"]},
     answers:{A:"Alexander Isak",B:5,C:6,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:6,G:"Lamine Yamal",H:"Brasilien"},tiebreaker:12,submitted:"26-06-05, 13:25"},
    {name:"Jimmy Pettersson",contact:{phone:"",email:""},
     picks:{"1":["2"],"2":["1","2"],"3":["1","2"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","2"],"13":["1","X"]},
     answers:{A:"Alexander Isak",B:4,C:3,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:4,G:"Julian Alvarez",H:"Argentina"},tiebreaker:12,submitted:"26-06-05, 13:31"},
    {name:"Martin Olofsson",contact:{phone:"",email:""},
     picks:{"1":["2"],"2":["1","2"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1","X"],"11":["X","2"],"12":["1","X"],"13":["2"]},
     answers:{A:"Alexander Isak",B:4,C:0,D:["Nederländerna","Tunisien"],E:["Frankrike","Senegal"],F:8,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:34,submitted:"26-06-05, 14:18"},
    {name:"Pelle Lindberg",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1"],"3":["1"],"4":["X","2"],"5":["1"],"6":["1"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1"],"11":["X","2"],"12":["X","2"],"13":["X","2"]},
     answers:{A:"Alexander Isak",B:5,C:4,D:["Nederländerna","Sverige"],E:["Frankrike","Senegal"],F:7,G:"Alexander Isak",H:"Argentina"},tiebreaker:33,submitted:"26-06-05, 14:28"},
    {name:"Christer Stridh",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1"],"9":["1"],"10":["1","X"],"11":["X","2"],"12":["1","2"],"13":["1"]},
     answers:{A:"Yasin Ayari",B:4,C:3,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:10,G:"Ferran Torres",H:"Spanien"},tiebreaker:44,submitted:"26-06-05, 14:45"},
    {name:"Julia Strid",contact:{phone:"",email:""},
     picks:{"1":["X"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","2"],"7":["1","2"],"8":["X","2"],"9":["1"],"10":["1","2"],"11":["2"],"12":["2"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:3,C:3,D:["Nederländerna","Sverige"],E:["Frankrike","Senegal"],F:5,G:"Kylian Mbappé",H:"Spanien"},tiebreaker:13,submitted:"26-06-05, 14:52"},
    {name:"Knåpen & Melle",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","2"],"8":["1","2"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","2"],"13":["2"]},
     answers:{A:"Alexander Isak",B:2,C:6,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:7,G:"Mikel Oyarzabal",H:"Spanien"},tiebreaker:41,submitted:"26-06-05, 17:23"},
    {name:"Uffe Tunong",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1","2"],"3":["1"],"4":["1"],"5":["1"],"6":["2"],"7":["1"],"8":["1","2"],"9":["1"],"10":["X","2"],"11":["2"],"12":["X","2"],"13":["1","X"]},
     answers:{A:"Taha Abdi Ali",B:2,C:5,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:3,G:"Lamine Yamal",H:"Spanien"},tiebreaker:61,submitted:"26-06-05, 20:27"},
    {name:"Johan Allgulander",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1","2"],"11":["2"],"12":["1","2"],"13":["X"]},
     answers:{A:"Alexander Isak",B:4,C:4,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:8,G:"VinciusJr",H:"Portugal"},tiebreaker:24,submitted:"26-06-07, 08:20"},
    {name:"Sven Olof Lindgren",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1","2"],"7":["1"],"8":["1","2"],"9":["1"],"10":["1","2"],"11":["2"],"12":["1","2"],"13":["1","X"]},
     answers:{A:"Alexander Isak",B:1,C:3,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:12,G:"Cristiano Ronaldo",H:"Brasilien"},tiebreaker:62,submitted:"26-06-07, 10:07"},
    {name:"Lotta Styrman",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1","2"],"9":["1"],"10":["1"],"11":["2"],"12":["X","2"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:1,C:4,D:["Sverige","Nederländerna"],E:["Frankrike","Norge"],F:5,G:"Kylian Mbappé",H:"Spanien"},tiebreaker:11,submitted:"26-06-07, 11:47"},
    {name:"Simon Grunnesjö",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1"],"4":["1","X"],"5":["1"],"6":["X","2"],"7":["X","2"],"8":["1","X"],"9":["1"],"10":["1"],"11":["2"],"12":["X","2"],"13":["2"]},
     answers:{A:"Viktor Gyökeres",B:4,C:6,D:["Japan","Nederländerna"],E:["Norge","Senegal"],F:8,G:"Igor Thiago",H:"Brasilien"},tiebreaker:25,submitted:"26-06-08, 11:25"},
    {name:"Frida Borin",contact:{phone:"",email:""},
     picks:{"1":["2"],"2":["1"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1"],"7":["1"],"8":["1","2"],"9":["1"],"10":["1","2"],"11":["1","2"],"12":["1","X"],"13":["1","2"]},
     answers:{A:"Anthony Elanga",B:5,C:7,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:13,G:"Kai Havertz",H:"England"},tiebreaker:43,submitted:"26-06-08, 21:08"},
    {name:"Jonathan Strid",contact:{phone:"",email:""},
     picks:{"1":["2"],"2":["1"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1"],"7":["1","X"],"8":["1","X"],"9":["1"],"10":["1"],"11":["1","2"],"12":["1","2"],"13":["1","2"]},
     answers:{A:"Alexander Isak",B:6,C:6,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:12,G:"Harry Kane",H:"Frankrike"},tiebreaker:37,submitted:"26-06-08, 21:17"},
    {name:"Tommie Bäcke",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","2"],"8":["1"],"9":["1"],"10":["1"],"11":["2"],"12":["1","2"],"13":["X","2"]},
     answers:{A:"Alexander Isak",B:2,C:5,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:11,G:"Harry Kane",H:"Spanien"},tiebreaker:26,submitted:"26-06-08, 22:07"},
    {name:"Håkan Larsson",contact:{phone:"",email:""},
     picks:{"1":["1"],"2":["1","2"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1"],"7":["1"],"8":["1","X"],"9":["1"],"10":["1"],"11":["X","2"],"12":["1","2"],"13":["1","X"]},
     answers:{A:"Viktor Gyökeres",B:4,C:2,D:["Japan","Nederländerna"],E:["Frankrike","Senegal"],F:8,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:64,submitted:"26-06-08, 23:32"},
    {name:"Niklas Ohlsson",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1","2"],"3":["1"],"4":["1"],"5":["1"],"6":["1"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1","2"],"11":["X","2"],"12":["1","2"],"13":["2"]},
     answers:{A:"Viktor Gyökeres",B:3,C:7,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:6,G:"Erling Haaland",H:"Frankrike"},tiebreaker:18,submitted:"26-06-09, 15:24"},
    {name:"John Söforth",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["X"],"9":["1"],"10":["1"],"11":["X","2"],"12":["1","X"],"13":["1","2"]},
     answers:{A:"Viktor Gyökeres",B:7,C:6,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:15,G:"Harry Kane",H:"England"},tiebreaker:44,submitted:"26-06-09, 21:56"},
    {name:"Pär Styrman",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1","X"],"9":["1"],"10":["1"],"11":["2"],"12":["X","2"],"13":["X","2"]},
     answers:{A:"Lucas Bergvall",B:4,C:3,D:["Japan","Sverige"],E:["Frankrike","Norge"],F:9,G:"Kylian Mbappé",H:"Spanien"},tiebreaker:21,submitted:"26-06-09, 23:35"},
    {name:"Andreas Smedbakken",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1","X"],"9":["1"],"10":["1"],"11":["2"],"12":["1","X"],"13":["2"]},
     answers:{A:"Viktor Gyökeres",B:6,C:4,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:16,G:"Harry Kane",H:"Spanien"},tiebreaker:40,submitted:"26-06-10, 08:50"},
    {name:"Jacob Barnholdt",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1","2"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","2"],"8":["1"],"9":["1"],"10":["1"],"11":["2"],"12":["1","X"],"13":["1","2"]},
     answers:{A:"Viktor Gyökeres",B:2,C:3,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:10,G:"Kylian Mbappé",H:"Spanien"},tiebreaker:35,submitted:"26-06-10, 08:52"},
    {name:"Fredrik Norberg",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1"],"3":["1","2"],"4":["1"],"5":["1"],"6":["1","X"],"7":["X","2"],"8":["1"],"9":["1"],"10":["1","2"],"11":["2"],"12":["X","2"],"13":["2"]},
     answers:{A:"Viktor Gyökeres",B:2,C:4,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:10,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:36,submitted:"26-06-10, 08:53"},
    {name:"Oscar Schilke",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:2,C:4,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:9,G:"Harry Kane",H:"Tyskland"},tiebreaker:26,submitted:"26-06-10, 09:30"},
    {name:"Lennart Berglund",contact:{phone:"",email:""},
     picks:{"1":["1"],"2":["1"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["X","2"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","X"],"13":["1","X"]},
     answers:{A:"Viktor Gyökeres",B:6,C:4,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:16,G:"Harry Kane",H:"Frankrike"},tiebreaker:59,submitted:"26-06-10, 12:47"},
    {name:"Marcus Aittamaa",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1"],"7":["1","2"],"8":["1","X"],"9":["1"],"10":["1"],"11":["X","2"],"12":["1"],"13":["X","2"]},
     answers:{A:"Alexander Isak",B:5,C:4,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:6,G:"Harry Kane",H:"Spanien"},tiebreaker:16,submitted:"26-06-10, 16:53"},
    {name:"Tomas Näslund",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1","X"],"9":["1"],"10":["X","2"],"11":["2"],"12":["1","2"],"13":["1"]},
     answers:{A:"Alexander Isak",B:2,C:6,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:5,G:"Erling Haaland",H:"Frankrike"},tiebreaker:18,submitted:"26-06-10, 17:03"},
    {name:"Linus Näslund",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["X","2"],"7":["X","2"],"8":["1","X"],"9":["1"],"10":["1","X"],"11":["1","X"],"12":["2"],"13":["2"]},
     answers:{A:"Viktor Gyökeres",B:4,C:5,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:7,G:"Didier Drogba",H:"Sverige"},tiebreaker:17,submitted:"26-06-10, 17:12"},
    {name:"Jessi Barka",contact:{phone:"",email:""},
     picks:{"1":["2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","X"],"13":["1","2"]},
     answers:{A:"Viktor Gyökeres",B:4,C:5,D:["Nederländerna","Japan"],E:["Frankrike","Norge"],F:8,G:"Kylian Mbappé",H:"Spanien"},tiebreaker:28,submitted:"26-06-10, 18:22"},
    {name:"Kalle Abrahamsson",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","2"],"8":["1","X"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","2"],"13":["2"]},
     answers:{A:"Alexander Isak",B:5,C:5,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:8,G:"Harry Kane",H:"England"},tiebreaker:37,submitted:"26-06-10, 20:23"},
    {name:"Kristian Fantenberg",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1"],"11":["X","2"],"12":["X","2"],"13":["1","2"]},
     answers:{A:"Alexander Isak",B:4,C:6,D:["Nederländerna","Japan"],E:["Frankrike","Norge"],F:9,G:"Harry Kane",H:"Frankrike"},tiebreaker:46,submitted:"26-06-11, 07:28"},
    {name:"Per Sandström",contact:{phone:"",email:""},
     picks:{"1":["X"],"2":["1"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1","X"],"9":["1"],"10":["1"],"11":["X","2"],"12":["2"],"13":["1","2"]},
     answers:{A:"Alexander Isak",B:2,C:3,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:12,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:47,submitted:"26-06-11, 13:24"},
    {name:"Filip Styrman",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["X","2"],"8":["1"],"9":["1"],"10":["1","X"],"11":["X","2"],"12":["1","X"],"13":["2"]},
     answers:{A:"Viktor Gyökeres",B:4,C:4,D:["Nederländerna","Japan"],E:["Frankrike","Norge"],F:8,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:31,submitted:"26-06-11, 14:58"},
    {name:"Philip Eriksén",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1","X"],"3":["X","2"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1","2"],"9":["1"],"10":["1"],"11":["2"],"12":["1","X"],"13":["2"]},
     answers:{A:"Viktor Gyökeres",B:0,C:6,D:["Nederländerna","Japan"],E:["Frankrike","Norge"],F:14,G:"Lamine Yamal",H:"Spanien"},tiebreaker:32,submitted:"26-06-11, 18:56"},
    {name:"Gunnar Månström",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1"],"7":["1","X"],"8":["1","X"],"9":["1"],"10":["1","X"],"11":["2"],"12":["X","2"],"13":["X"]},
     answers:{A:"Alexander Isak",B:3,C:2,D:["Nederländerna","Japan"],E:["Frankrike","Senegal"],F:7,G:"Mikel Oyarzabal",H:"Frankrike"},tiebreaker:27,submitted:"26-06-11, 19:16"},
    {name:"Olle Skoglund",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1"],"3":["1"],"4":["1"],"5":["1","X"],"6":["X","2"],"7":["1","X"],"8":["1","X"],"9":["1"],"10":["1"],"11":["2"],"12":["X","2"],"13":["2"]},
     answers:{A:"Viktor Gyökeres",B:3,C:8,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:12,G:"Erling Haaland",H:"Spanien"},tiebreaker:22,submitted:"26-06-11, 19:22"},
    {name:"Kenneth & Jon",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1","X"],"4":["1","2"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1"],"9":["1"],"10":["1"],"11":["1","2"],"12":["X","2"],"13":["1"]},
     answers:{A:"Yasin Ayari",B:4,C:3,D:["Nederländerna","Sverige"],E:["Frankrike","Senegal"],F:9,G:"Kai Havertz",H:"Tyskland"},tiebreaker:34,submitted:"26-06-11, 20:44"},
    {name:"Peter Forsström",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1"],"7":["1"],"8":["1","X"],"9":["1"],"10":["1","X"],"11":["1","2"],"12":["X","2"],"13":["X","2"]},
     answers:{A:"Anthony Elanga",B:5,C:7,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:5,G:"Erling Haaland",H:"Frankrike"},tiebreaker:30,submitted:"26-06-11, 21:09"},
    {name:"Erik Andersson",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1","2"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1"],"11":["2"],"12":["1","X"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:3,C:3,D:["Nederländerna","Japan"],E:["Frankrike","Senegal"],F:9,G:"Harry Kane",H:"Spanien"},tiebreaker:28,submitted:"26-06-11, 21:28"},
    {name:"Kent-Ola Backlund",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1"],"4":["1","X"],"5":["1"],"6":["1"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1","2"],"11":["X","2"],"12":["X","2"],"13":["2"]},
     answers:{A:"Viktor Gyökeres",B:6,C:5,D:["Nederländerna","Sverige"],E:["Frankrike","Senegal"],F:12,G:"Harry Kane",H:"England"},tiebreaker:34,submitted:"26-06-11, 21:44"},
    {name:"Anders Lindberg",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1"],"4":["1","X"],"5":["1"],"6":["1"],"7":["1","2"],"8":["1","X"],"9":["1"],"10":["1","X"],"11":["2"],"12":["X"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:4,C:4,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:16,G:"Lionel Messi",H:"Spanien"},tiebreaker:36,submitted:"26-06-11, 21:44"},
    {name:"Jan-Åke Svensson",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1"],"3":["1"],"4":["1","X"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","2"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:3,C:4,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:4,G:"Kylian Mbappé",H:"Argentina"},tiebreaker:15,submitted:"26-06-12, 20:45"},
    {name:"Hasse Jonsson",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1","X"],"9":["1"],"10":["1"],"11":["X","2"],"12":["X","2"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:2,C:3,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:3,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:9,submitted:"26-06-12, 23:09"},
    {name:"Robert Örnehag",contact:{phone:"",email:""},
     picks:{"1":["X"],"2":["1"],"3":["1"],"4":["1","X"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1","X"],"11":["X","2"],"12":["2"],"13":["X","2"]},
     answers:{A:"Alexander Isak",B:6,C:3,D:["Nederländerna","Sverige"],E:["Frankrike","Senegal"],F:12,G:"Ollie Watkins",H:"England"},tiebreaker:29,submitted:"26-06-13, 15:17"},
    {name:"Mats Hansson",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1"],"9":["1"],"10":["1","X"],"11":["2"],"12":["X","2"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:4,C:3,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:7,G:"Kylian Mbappé",H:"Spanien"},tiebreaker:23,submitted:"26-06-13, 18:08"},
    {name:"Carina Svensk",contact:{phone:"",email:""},
     picks:{"1":["1"],"2":["1","X"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1"],"7":["1","X"],"8":["1"],"9":["1"],"10":["X","2"],"11":["X","2"],"12":["2"],"13":["1","2"]},
     answers:{A:"Alexander Isak",B:3,C:7,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:4,G:"Harry Kane",H:"Frankrike"},tiebreaker:34,submitted:"26-06-13, 18:41"},
    {name:"Mats Abrahamsson",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","X"],"13":["X","2"]},
     answers:{A:"Alexander Isak",B:4,C:5,D:["Nederländerna","Japan"],E:["Frankrike","Norge"],F:5,G:"Kylian Mbappé",H:"Spanien"},tiebreaker:27,submitted:"26-06-13, 19:13"},
    {name:"Johanna Örnehag",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1"],"4":["1","2"],"5":["1"],"6":["1"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1","2"],"11":["1","2"],"12":["2"],"13":["X","2"]},
     answers:{A:"Lukas Bergwall",B:2,C:3,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:9,G:"Ousmane Dembélé",H:"Frankrike"},tiebreaker:26,submitted:"26-06-14, 08:01"},
    {name:"Karl Fredriksson",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["X","2"],"8":["1","X"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","2"],"13":["X"]},
     answers:{A:"Alexander Isak",B:5,C:6,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:8,G:"Harry Kane",H:"Frankrike"},tiebreaker:43,submitted:"26-06-14, 10:23"},
    {name:"Patrik Dahlin",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1"],"9":["1"],"10":["2"],"11":["X","2"],"12":["X","2"],"13":["X","2"]},
     answers:{A:"Alexander Isak",B:7,C:3,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:5,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:23,submitted:"26-06-14, 10:30"},
    {name:"Jonatan Westner",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1","2"],"3":["1"],"4":["1"],"5":["1"],"6":["1"],"7":["1","X"],"8":["1","2"],"9":["1"],"10":["1","X"],"11":["2"],"12":["2"],"13":["X","2"]},
     answers:{A:"Taha Ali",B:3,C:4,D:["Nederländerna","Japan"],E:["Frankrike","Norge"],F:3,G:"Harry Kane",H:"Brasilien"},tiebreaker:33,submitted:"26-06-14, 11:27"},
    {name:"Bosse Jakobsson",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1"],"7":["X","2"],"8":["1","X"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:5,C:2,D:["Nederländerna","Japan"],E:["Frankrike","Norge"],F:9,G:"Folarin Balogun",H:"Frankrike"},tiebreaker:33,submitted:"26-06-14, 11:32"},
    {name:"Viktor Örnehag",contact:{phone:"",email:""},
     picks:{"1":["1"],"2":["1"],"3":["1"],"4":["1","X"],"5":["1"],"6":["1","2"],"7":["X","2"],"8":["1"],"9":["1"],"10":["1","X"],"11":["X","2"],"12":["X","2"],"13":["2"]},
     answers:{A:"Alexander Isak",B:5,C:6,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:7,G:"Kylian Mbappé",H:"England"},tiebreaker:43,submitted:"26-06-14, 11:52"},
    {name:"Clas Bodin",contact:{phone:"",email:""},
     picks:{"1":["X"],"2":["1","X"],"3":["1"],"4":["1","X"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1","2"],"11":["2"],"12":["2"],"13":["1","X"]},
     answers:{A:"Alexander Isak",B:5,C:7,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:8,G:"Erling Haaland",H:"Spanien"},tiebreaker:32,submitted:"26-06-14, 13:13"},
    {name:"Claes-Göran Dahlberg",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1"],"7":["1","X"],"8":["1","X"],"9":["1"],"10":["1","2"],"11":["X","2"],"12":["X"],"13":["1"]},
     answers:{A:"Viktor Gyökeres",B:4,C:5,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:12,G:"Kylian Mbappé",H:"Spanien"},tiebreaker:20,submitted:"26-06-14, 15:08"},
    {name:"Anders Axelsson",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1"],"7":["1"],"8":["1","X"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","2"],"13":["X","2"]},
     answers:{A:"Alexander Isak",B:4,C:5,D:["Nederländerna","Japan"],E:["Frankrike","Norge"],F:8,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:8,submitted:"26-06-14, 17:09"},
    {name:"Eric Roth",contact:{phone:"",email:""},
     picks:{"1":["1"],"2":["1","2"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","2"],"8":["1"],"9":["1"],"10":["1","X"],"11":["2"],"12":["X"],"13":["1","2"]},
     answers:{A:"Viktor Gyökeres",B:5,C:4,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:9,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:46,submitted:"26-06-14, 19:08"},
    {name:"Axel Örnehag",contact:{phone:"",email:""},
     picks:{"1":["2"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1","X"],"9":["1"],"10":["1","2"],"11":["X","2"],"12":["X","2"],"13":["1","X"]},
     answers:{A:"Viktor Gyökeres",B:5,C:5,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:17,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:39,submitted:"26-06-14, 19:21"},
    {name:"Andreas Selin",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1","X"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1","X"],"7":["2"],"8":["1","X"],"9":["1"],"10":["X"],"11":["2"],"12":["1"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:4,C:6,D:["Nederländerna","Japan"],E:["Frankrike","Norge"],F:11,G:"Harry Kane",H:"Frankrike"},tiebreaker:37,submitted:"26-06-14, 19:24"},
    {name:"Jhonny Nordlund",contact:{phone:"",email:""},
     picks:{"1":["2"],"2":["1","2"],"3":["1","2"],"4":["1","X"],"5":["1"],"6":["1","2"],"7":["1"],"8":["1","X"],"9":["1"],"10":["1","X"],"11":["2"],"12":["2"],"13":["2"]},
     answers:{A:"Anthony Elanga",B:1,C:5,D:["Nederländerna","Sverige"],E:["Frankrike","Senegal"],F:12,G:"Lionel Messi",H:"Argentina"},tiebreaker:11,submitted:"26-06-14, 19:43"},
    {name:"Per Lundin",contact:{phone:"",email:""},
     picks:{"1":["1"],"2":["X","2"],"3":["1"],"4":["1"],"5":["1"],"6":["1","2"],"7":["X","2"],"8":["1","X"],"9":["1"],"10":["1"],"11":["X","2"],"12":["X"],"13":["1","X"]},
     answers:{A:"Alexander Isak",B:2,C:3,D:["Nederländerna","Japan"],E:["Frankrike","Norge"],F:4,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:26,submitted:"26-06-14, 19:58"},
    {name:"Josephine Näslund",contact:{phone:"",email:""},
     picks:{"1":["2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","2"],"8":["1","X"],"9":["1"],"10":["1","X"],"11":["2"],"12":["X","2"],"13":["2"]},
     answers:{A:"Viktor Gyökeres",B:3,C:6,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:15,G:"Erling Haaland",H:"Norge"},tiebreaker:40,submitted:"26-06-14, 20:17"},
    {name:"Jan Fagerström",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1","X"],"9":["1"],"10":["1"],"11":["X","2"],"12":["X","2"],"13":["2"]},
     answers:{A:"Alexander Isak",B:2,C:3,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:13,G:"Ferran Torres",H:"Spanien"},tiebreaker:57,submitted:"26-06-14, 20:35"},
    {name:"Pär Söderström",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1"],"3":["1","X"],"4":["1","X"],"5":["1"],"6":["X"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1","X"],"11":["X"],"12":["X"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:3,C:5,D:["Japan","Sverige"],E:["Frankrike","Norge"],F:13,G:"Erling Haaland",H:"Norge"},tiebreaker:37,submitted:"26-06-14, 20:37"},
    {name:"Erik Berglund",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["X"],"7":["1","2"],"8":["1"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","X"],"13":["X","2"]},
     answers:{A:"Yasin Ayari",B:4,C:3,D:["Nederländerna","Japan"],E:["Frankrike","Norge"],F:8,G:"Folarin Balogun",H:"Frankrike"},tiebreaker:22,submitted:"26-06-14, 20:41"},
    {name:"Albert Stål",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","2"],"7":["1","X"],"8":["1","2"],"9":["1"],"10":["1"],"11":["2"],"12":["1","2"],"13":["2"]},
     answers:{A:"Viktor Gyökeres",B:3,C:5,D:["Nederländerna","Japan"],E:["Frankrike","Norge"],F:13,G:"Harry Kane",H:"Spanien"},tiebreaker:38,submitted:"26-06-14, 20:51"},
    {name:"Lars-Åke Persson",contact:{phone:"",email:""},
     picks:{"1":["2"],"2":["1","X"],"3":["1"],"4":["1","2"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1","2"],"9":["1"],"10":["1"],"11":["2"],"12":["1","X"],"13":["2"]},
     answers:{A:"Anthony Elanga",B:4,C:4,D:["Nederländerna","Japan"],E:["Frankrike","Norge"],F:11,G:"Kylian Mbappé",H:"Spanien"},tiebreaker:52,submitted:"26-06-14, 20:59"},
    {name:"Kogge",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1"],"3":["X","2"],"4":["1","2"],"5":["1"],"6":["1"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1"],"11":["X","2"],"12":["2"],"13":["X","2"]},
     answers:{A:"Benjamin Nygren",B:2,C:4,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:6,G:"Harry Kane",H:"Portugal"},tiebreaker:38,submitted:"26-06-14, 21:42"},
    {name:"Thomas Händel",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1","2"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","2"],"13":["2"]},
     answers:{A:"Alexander Isak",B:3,C:5,D:["Nederländerna","Japan"],E:["Frankrike","Norge"],F:10,G:"Michael Olise",H:"Portugal"},tiebreaker:22,submitted:"26-06-14, 21:56"},
    {name:"Gustav Bergshem",contact:{phone:"",email:""},
     picks:{"1":["2"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1","2"],"11":["X","2"],"12":["X","2"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:6,C:4,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:9,G:"Kai Havertz",H:"Frankrike"},tiebreaker:40,submitted:"26-06-14, 22:47"},
    {name:"Gustav Dahlin",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["X","2"],"4":["1"],"5":["1","X"],"6":["X","2"],"7":["X","2"],"8":["1"],"9":["1"],"10":["1"],"11":["2"],"12":["X","2"],"13":["2"]},
     answers:{A:"Benjamin Nygren",B:5,C:6,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:11,G:"Erling Haaland",H:"Frankrike"},tiebreaker:35,submitted:"26-06-14, 22:58"},
    {name:"Fredrik Ohlsson",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1"],"3":["X","2"],"4":["1"],"5":["1"],"6":["1"],"7":["1"],"8":["X","2"],"9":["1"],"10":["1","2"],"11":["2"],"12":["1","X"],"13":["X","2"]},
     answers:{A:"Isak Hien",B:7,C:5,D:["Nederländerna","Japan"],E:["Frankrike","Norge"],F:10,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:49,submitted:"26-06-14, 23:09"},
    {name:"Tirvan Ali",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1","2"],"7":["1"],"8":["1"],"9":["1"],"10":["1","X"],"11":["2"],"12":["X","2"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:0,C:5,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:4,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:6,submitted:"26-06-14, 23:13"},
    {name:"Leo Feichtinger",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["X","2"],"8":["1","X"],"9":["1"],"10":["1"],"11":["X","2"],"12":["1","X"],"13":["2"]},
     answers:{A:"Alexander Isak",B:4,C:5,D:["Nederländerna","Japan"],E:["Frankrike","Norge"],F:9,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:13,submitted:"26-06-14, 23:34"},
    {name:"Anders Östlund",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["X","2"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1","2"],"9":["1"],"10":["1"],"11":["X","2"],"12":["1"],"13":["X","2"]},
     answers:{A:"Alexander Isak",B:5,C:6,D:["Nederländerna","Japan"],E:["Frankrike","Norge"],F:12,G:"Ferran Torres",H:"Spanien"},tiebreaker:32},
    ],
  live_stats: {
    penalties: 10,
    haaland_goals: 4,
    et_matches: 0,
    top_scorers: [
      {player:"Lionel Messi",          country:"Argentina 🇦🇷",               goals:5},
      {player:"Vinícius Júnior",       country:"Brasilien 🇧🇷",               goals:4},
      {player:"Kylian Mbappé",         country:"Frankrike 🇫🇷",               goals:4},
      {player:"Ousmane Dembélé",       country:"Frankrike 🇫🇷",               goals:4},
      {player:"Erling Haaland",        country:"Norge 🇳🇴",                   goals:4},
      {player:"Matheus Cunha",         country:"Brasilien 🇧🇷",               goals:3},
      {player:"Harry Kane",            country:"England 🏴󠁧󠁢󠁥󠁮󠁧󠁿",                 goals:3},
      {player:"Yoane Wissa",           country:"DR Kongo 🇨🇩",                goals:3},
      {player:"Jonathan David",        country:"Kanada 🇨🇦",                  goals:3},
      {player:"Ismael Saibari",        country:"Marocko 🇲🇦",                 goals:3},
      {player:"Cody Gakpo",            country:"Nederländerna 🇳🇱",           goals:3},
      {player:"Elijah Just",           country:"Nya Zeeland 🇳🇿",             goals:3},
      {player:"Johan Manzambi",        country:"Schweiz 🇨🇭",                 goals:3},
      {player:"Ismaïla Sarr",          country:"Senegal 🇸🇳",                 goals:3},
      {player:"Deniz Undav",           country:"Tyskland 🇩🇪",                goals:3},
      {player:"Leandro Trossard",      country:"Belgien 🇧🇪",                 goals:2},
      {player:"Ermin Mahmic",          country:"Bosnien och Herzegovina 🇧🇦", goals:2},
      {player:"Daniel Muñoz",          country:"Colombia 🇨🇴",                goals:2},
      {player:"Nicolas Pépé",          country:"Elfenbenskusten 🇨🇮",         goals:2},
      {player:"Jude Bellingham",       country:"England 🏴󠁧󠁢󠁥󠁮󠁧󠁿",                 goals:2},
      {player:"Ramin Rezaeian",        country:"Iran 🇮🇷",                    goals:2},
      {player:"Ayase Ueda",            country:"Japan 🇯🇵",                   goals:2},
      {player:"Daichi Kamada",         country:"Japan 🇯🇵",                   goals:2},
      {player:"Cyle Larin",            country:"Kanada 🇨🇦",                  goals:2},
      {player:"Julián Quiñones",       country:"Mexiko 🇲🇽",                  goals:2},
      {player:"Brian Brobbey",         country:"Nederländerna 🇳🇱",           goals:2},
      {player:"Crysencio Summerville", country:"Nederländerna 🇳🇱",           goals:2},
      {player:"Cristiano Ronaldo",     country:"Portugal 🇵🇹",                goals:2},
      {player:"Rubén Vargas",          country:"Schweiz 🇨🇭",                 goals:2},
      {player:"Pape Gueye",            country:"Senegal 🇸🇳",                 goals:2},
      {player:"Mikel Oyarzabal",       country:"Spanien 🇪🇸",                 goals:2},
      {player:"Anthony Elanga",        country:"Sverige 🇸🇪",                 goals:2},
      {player:"Yasin Ayari",           country:"Sverige 🇸🇪",                 goals:2},
      {player:"Kai Havertz",           country:"Tyskland 🇩🇪",                goals:2},
      {player:"Maximiliano Araújo",    country:"Uruguay 🇺🇾",                 goals:2},
      {player:"Folarin Balogun",       country:"USA 🇺🇸",                     goals:2},
      {player:"Självmål",              country:"USA 🇺🇸",                     goals:2},
      {player:"Amine Gouiri",          country:"Algeriet 🇩🇿",                goals:1},
      {player:"Nadhir Benbouali",      country:"Algeriet 🇩🇿",                goals:1},
      {player:"Connor Metcalfe",       country:"Australien 🇦🇺",              goals:1},
      {player:"Nestory Irankunda",     country:"Australien 🇦🇺",              goals:1},
      {player:"Àlexis Saelemaekers",   country:"Belgien 🇧🇪",                 goals:1},
      {player:"Kevin De Bruyne",       country:"Belgien 🇧🇪",                 goals:1},
      {player:"Romelu Lukaku",         country:"Belgien 🇧🇪",                 goals:1},
      {player:"Självmål",              country:"Belgien 🇧🇪",                 goals:1},
      {player:"Kermin Alajbegovic",    country:"Bosnien och Herzegovina 🇧🇦", goals:1},
      {player:"Jovo Lukic",            country:"Bosnien och Herzegovina 🇧🇦", goals:1},
      {player:"Självmål",              country:"Bosnien och Herzegovina 🇧🇦", goals:1},
      {player:"Jaminton Campaz",       country:"Colombia 🇨🇴",                goals:1},
      {player:"Luis Díaz",             country:"Colombia 🇨🇴",                goals:1},
      {player:"Livano Comenencia",     country:"Curaçao 🇨🇼",                 goals:1},
      {player:"Fiston Mayele",         country:"DR Kongo 🇨🇩",                goals:1},
      {player:"Gonzalo Plata",         country:"Ecuador 🇪🇨",                 goals:1},
      {player:"Nilson Angulo",         country:"Ecuador 🇪🇨",                 goals:1},
      {player:"Emam Ashour",           country:"Egypten 🇪🇬",                 goals:1},
      {player:"Mahmoud Saber",         country:"Egypten 🇪🇬",                 goals:1},
      {player:"Mohamed Salah",         country:"Egypten 🇪🇬",                 goals:1},
      {player:"Mostafa Zico",          country:"Egypten 🇪🇬",                 goals:1},
      {player:"Trezeguet",             country:"Egypten 🇪🇬",                 goals:1},
      {player:"Amad Diallo",           country:"Elfenbenskusten 🇨🇮",         goals:1},
      {player:"Franck Kessié",         country:"Elfenbenskusten 🇨🇮",         goals:1},
      {player:"Marcus Rashford",       country:"England 🏴󠁧󠁢󠁥󠁮󠁧󠁿",                 goals:1},
      {player:"Bradley Barcola",       country:"Frankrike 🇫🇷",               goals:1},
      {player:"Désiré Doué",           country:"Frankrike 🇫🇷",               goals:1},
      {player:"Caleb Yirenkyi",        country:"Ghana 🇬🇭",                   goals:1},
      {player:"Derrick 'luckassen",    country:"Ghana 🇬🇭",                   goals:1},
      {player:"Självmål",              country:"Haiti 🇭🇹",                   goals:1},
      {player:"Wilson Isidor",         country:"Haiti 🇭🇹",                   goals:1},
      {player:"Aymen Hussein",         country:"Irak 🇮🇶",                    goals:1},
      {player:"Mohammad Mohebi",       country:"Iran 🇮🇷",                    goals:1},
      {player:"Daizen Maeda",          country:"Japan 🇯🇵",                   goals:1},
      {player:"Junya Ito",             country:"Japan 🇯🇵",                   goals:1},
      {player:"Keito Nakamura",        country:"Japan 🇯🇵",                   goals:1},
      {player:"Ali Olwan",             country:"Jordanien 🇯🇴",               goals:1},
      {player:"Nizar Al Rashdan",      country:"Jordanien 🇯🇴",               goals:1}, 
      {player:"Nathan Saliba",         country:"Kanada 🇨🇦",                  goals:1},
      {player:"Promise David",         country:"Kanada 🇨🇦",                  goals:1},
      {player:"Självmål",              country:"Kanada 🇨🇦",                  goals:1},
      {player:"Hélio Varela",          country:"Kap Verde 🇨🇻",               goals:1},
      {player:"Kevin Pina",            country:"Kap Verde 🇨🇻",               goals:1},
      {player:"Ante Budimir",          country:"Kroatien 🇭🇷",                goals:1},
      {player:"Martin Baturina",       country:"Kroatien 🇭🇷",                goals:1},
      {player:"Nikola Vlasic",         country:"Kroatien 🇭🇷",                goals:1},
      {player:"Petar Musa",            country:"Kroatien 🇭🇷",                goals:1},
      {player:"Petar Sucic",           country:"Kroatien 🇭🇷",                goals:1},
      {player:"Achraf Hakimi",         country:"Marocko 🇲🇦",                 goals:1},
      {player:"Gessime Yassine",       country:"Marocko 🇲🇦",                 goals:1},
      {player:"Soufiane Rahimi",       country:"Marocko 🇲🇦",                 goals:1},
      {player:"Àlvaro Fidalgo",        country:"Mexiko 🇲🇽",                  goals:1},
      {player:"Luis Romo",             country:"Mexiko 🇲🇽",                  goals:1},
      {player:"Mateo Chávez",          country:"Mexiko 🇲🇽",                  goals:1},
      {player:"Raúl Jiménez",          country:"Mexiko 🇲🇽",                  goals:1},
      {player:"Jan Paul van Hecke",    country:"Nederländerna 🇳🇱",           goals:1},
      {player:"Självmål",              country:"Nederländerna 🇳🇱",           goals:1},
      {player:"Virgil van Dijk",       country:"Nederländerna 🇳🇱",           goals:1},
      {player:"Leo Østigård",          country:"Norge 🇳🇴",                   goals:1},
      {player:"Marcus Pedersen",       country:"Norge 🇳🇴",                   goals:1},
      {player:"Självmål",              country:"Norge 🇳🇴",                   goals:1},
      {player:"Thelo Aasgaard",        country:"Norge 🇳🇴",                   goals:1},
      {player:"Finn Surman",           country:"Nya Zeeland 🇳🇿",             goals:1},
      {player:"Matías Galarza",        country:"Paraguay 🇵🇾",                goals:1},
      {player:"Maurício",              country:"Paraguay 🇵🇾",                goals:1},
      {player:"João Neves",            country:"Portugal 🇵🇹",                goals:1},
      {player:"Nuno Mendes",           country:"Portugal 🇵🇹",                goals:1},
      {player:"Rafael Leão",           country:"Portugal 🇵🇹",                goals:1},
      {player:"Självmål",              country:"Portugal 🇵🇹",                goals:1},
      {player:"Hassan Al Haydos",      country:"Qatar 🇶🇦",                   goals:1},
      {player:"Självmål",              country:"Qatar 🇶🇦",                   goals:1},
      {player:"Abdulelah Al-Amri",     country:"Saudiarabien 🇸🇦",            goals:1},
      {player:"Breel Embolo",          country:"Schweiz 🇨🇭",                 goals:1},
      {player:"Granit Xhaka",          country:"Schweiz 🇨🇭",                 goals:1},
      {player:"Ibrahim Mbaye",         country:"Senegal 🇸🇳",                 goals:1},
      {player:"Iliman Ndiaye",         country:"Senegal 🇸🇳",                 goals:1},
      {player:"Habib Diarra",          country:"Senegal 🇸🇳",                 goals:1},
      {player:"John McGinn",           country:"Skottland 🏴󠁧󠁢󠁳󠁣󠁴󠁿",               goals:1},
      {player:"Àlex Baena",            country:"Spanien 🇪🇸",                 goals:1},
      {player:"Lamine Yamal",          country:"Spanien 🇪🇸",                 goals:1},
      {player:"Självmål",              country:"Spanien 🇪🇸",                 goals:1},
      {player:"Alexander Isak",        country:"Sverige 🇸🇪",                 goals:1},
      {player:"Mattias Svanberg",      country:"Sverige 🇸🇪",                 goals:1},
      {player:"Viktor Gyökeres",       country:"Sverige 🇸🇪",                 goals:1},
      {player:"Teboho Mokoena",        country:"Sydafrika 🇿🇦",               goals:1},
      {player:"Thapelo Maseko",        country:"Sydafrika 🇿🇦",               goals:1},
      {player:"Hwang In-Beom",         country:"Sydkorea 🇰🇷",                goals:1},
      {player:"Oh Hyeon-gyu",          country:"Sydkorea 🇰🇷",                goals:1},
      {player:"Ladislav Krejci",       country:"Tjeckien 🇨🇿",                goals:1},
      {player:"Michal Sadílek",        country:"Tjeckien 🇨🇿",                goals:1},
      {player:"Hazem Mastouri",        country:"Tunisien 🇹🇳",                goals:1},
      {player:"Omar Rekik",            country:"Tunisien 🇹🇳",                goals:1},
      {player:"Arda Güler",            country:"Turkiet 🇹🇷",                 goals:1},
      {player:"Kaan Ayhan",            country:"Turkiet 🇹🇷",                 goals:1},
      {player:"Orkun Kökçü",           country:"Turkiet 🇹🇷",                 goals:1},
      {player:"Felix Nmecha",          country:"Tyskland 🇩🇪",                goals:1},
      {player:"Jamal Musiala",         country:"Tyskland 🇩🇪",                goals:1},
      {player:"Leroy Sané",            country:"Tyskland 🇩🇪",                goals:1},
      {player:"Nathaniel Brown",       country:"Tyskland 🇩🇪",                goals:1},
      {player:"Nico Schlotterbeck",    country:"Tyskland 🇩🇪",                goals:1},
      {player:"Agustín Canobbio",      country:"Uruguay 🇺🇾",                 goals:1},
      {player:"Alex Freeman",          country:"USA 🇺🇸",                     goals:1},
      {player:"Auston Trusty",         country:"USA 🇺🇸",                     goals:1},
      {player:"Giovanni Reyna",        country:"USA 🇺🇸",                     goals:1},
      {player:"Sebastian Berhalter",   country:"USA 🇺🇸",                     goals:1},
      {player:"Abbosbek Fayzullaev",   country:"Uzbekistan 🇺🇿",              goals:1},
      {player:"Eldor Shomurodov",      country:"Uzbekistan 🇺🇿",              goals:1},
      {player:"Marko Arnautovic",      country:"Österrike 🇦🇹",               goals:1},
      {player:"Romano Schmid",         country:"Österrike 🇦🇹",               goals:1},
      {player:"Självmål",              country:"Österrike 🇦🇹",               goals:1}
    ]
  }
};

POOL_DATA.meta.admin_password = "Admin-inloggning";

if (typeof window !== "undefined") window.POOL_DATA = POOL_DATA;
if (typeof module !== "undefined" && module.exports) module.exports = POOL_DATA;
