/* VM-tipset 2026 — publik data (inga kontaktuppgifter) */
const POOL_DATA = {
  meta: {
    title: "VM-tipset 2026",
    organizer: "Christer",
    swish: "070 693 99 70",
    cost_sek: 100,
    deadline: "2026-06-14T23:59:00+02:00",
    prize_split: { "1": 0.65, "2": 0.25, "3": 0.10 },
    show_countdown: true
  },
  matches: [
    { id: 1,  kickoff: "2026-06-15T01:00", home: "Elfenbenskusten", away: "Ecuador",      result: null },
    { id: 2,  kickoff: "2026-06-15T04:00", home: "Sverige",         away: "Tunisien",     result: null },
    { id: 3,  kickoff: "2026-06-15T21:00", home: "Belgien",         away: "Egypten",      result: null },
    { id: 4,  kickoff: "2026-06-16T21:00", home: "Frankrike",       away: "Senegal",      result: null },
    { id: 5,  kickoff: "2026-06-17T19:00", home: "Portugal",        away: "DR Kongo",     result: null },
    { id: 6,  kickoff: "2026-06-17T22:00", home: "England",         away: "Kroatien",     result: null },
    { id: 7,  kickoff: "2026-06-19T03:00", home: "Mexiko",          away: "Sydkorea",     result: null },
    { id: 8,  kickoff: "2026-06-19T21:00", home: "USA",             away: "Australien",   result: null },
    { id: 9,  kickoff: "2026-06-21T18:00", home: "Spanien",         away: "Saudiarabien", result: null },
    { id: 10, kickoff: "2026-06-24T21:00", home: "Schweiz",         away: "Kanada",       result: null },
    { id: 11, kickoff: "2026-06-25T00:00", home: "Skottland",       away: "Brasilien",    result: null },
    { id: 12, kickoff: "2026-06-26T01:00", home: "Japan",           away: "Sverige",      result: null },
    { id: 13, kickoff: "2026-06-28T04:00", home: "Algeriet",        away: "Österrike",    result: null }
  ],
  questions: [
    { id: "A", type: "text",    points: 2,              prompt: "Vem gör Sveriges första mål i VM?",                                                                                   correct: null },
    { id: "B", type: "number",  points: 2, tolerance: 0, prompt: "Hur många gula kort blir det i Argentina–Österrike? (mån 22 juni 19:00)",                                           correct: null },
    { id: "C", type: "number",  points: 2, tolerance: 0, prompt: "Hur många mål gör Erling Haaland i VM? (mål under avgörande straffläggning räknas EJ)",                             correct: null },
    { id: "D", type: "twoteam", points: 4, scoring: "per_team_unordered", prompt: "Vilka två lag kommer 1:a och 2:a i grupp F?", options: ["Nederländerna","Japan","Sverige","Tunisien"], correct: null },
    { id: "E", type: "twoteam", points: 4, scoring: "per_team_unordered", prompt: "Vilka två lag kommer 1:a och 2:a i grupp I?", options: ["Frankrike","Iran","Norge","Senegal"],      correct: null },
    { id: "F", type: "number",  points: 2, tolerance: 1, prompt: "Hur många av slutspelets 32 matcher går till förlängning eller straffläggning?<br>(+/- 1 match ger rätt)",             correct: null },
    { id: "G", type: "text",    points: 2,              prompt: "Vem vinner VM:s skytteliga? (delad skytteligavinst räknas som korrekt)",                                             correct: null },
    { id: "H", type: "text",    points: 2,              prompt: "Vilket land blir världsmästare?",                                                                                     correct: null }
  ],
  tiebreaker: {
    type: "number_closest",
    prompt: "Hur många straffar blir det under VM? (gäller ordinarie tid + förlängning, EJ straffläggningar)",
    correct: null
  },
  participants: [
    {name:"Solveig Norin",contact:{phone:"",email:""},
     picks:{"1":["1"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1","X"],"9":["1"],"10":["X","2"],"11":["2"],"12":["X","2"],"13":["1","2"]},
     answers:{A:"Viktor Gyökeres",B:3,C:3,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:4,G:"Lamine Yamal",H:"Spanien"},tiebreaker:24},
    {name:"Hans Erixon",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","2"],"8":["X"],"9":["1"],"10":["1","2"],"11":["2"],"12":["1","X"],"13":["1","X"]},
     answers:{A:"Sverige gör inga mål",B:3,C:5,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:9,G:"Erling Haaland",H:"Spanien"},tiebreaker:12},
    {name:"Gabriel Popanicic",contact:{phone:"",email:""},
     picks:{"1":["1"],"2":["1","X"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1","2"],"9":["1"],"10":["1"],"11":["2"],"12":["X","2"],"13":["2"]},
     answers:{A:"Alexander Isak",B:3,C:5,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:8,G:"Ousmane Dembele",H:"Frankrike"},tiebreaker:38},
    {name:"Felix Olsson",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1"],"7":["1","X"],"8":["1","X"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","X"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:4,C:3,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:7,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:28},
    {name:"Love Olsson",contact:{phone:"",email:""},
     picks:{"1":["1"],"2":["X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1","X"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","X"],"13":["1","2"]},
     answers:{A:"Isak Hien",B:7,C:3,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:4,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:23},
    {name:"Mats Erik Persson",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1"],"3":["1"],"4":["1","X"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1"],"11":["X","2"],"12":["1","X"],"13":["2"]},
     answers:{A:"Alexander Isak",B:3,C:4,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:14,G:"Erling Haaland",H:"Norge"},tiebreaker:22},
    {name:"Johan Åkerlund",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1"],"7":["X","2"],"8":["1"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","X"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:5,C:4,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:8,G:"Harry Kane",H:"Spanien"},tiebreaker:42},
    {name:"Tomas Flodin",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1","X"],"9":["1"],"10":["1"],"11":["X","2"],"12":["2"],"13":["1","2"]},
     answers:{A:"Viktor Gyökeres",B:4,C:7,D:["Nederländerna","Sverige"],E:["Frankrike","Senegal"],F:8,G:"Erling Haaland",H:"Brasilien"},tiebreaker:30},
    {name:"Mats Ståby",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["X","2"],"3":["1"],"4":["1","X"],"5":["1"],"6":["1","2"],"7":["1"],"8":["1"],"9":["1"],"10":["1"],"11":["X","2"],"12":["1"],"13":["X","2"]},
     answers:{A:"Alexander Isak",B:5,C:6,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:6,G:"Lamine Yamal",H:"Brasilien"},tiebreaker:12},
    {name:"Jimmy Pettersson",contact:{phone:"",email:""},
     picks:{"1":["2"],"2":["1","2"],"3":["1","2"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","2"],"13":["1","X"]},
     answers:{A:"Alexander Isak",B:4,C:3,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:4,G:"Julian Alvarez",H:"Argentina"},tiebreaker:12},
    {name:"Martin Olofsson",contact:{phone:"",email:""},
     picks:{"1":["2"],"2":["1","2"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1","X"],"11":["X","2"],"12":["1","X"],"13":["2"]},
     answers:{A:"Alexander Isak",B:4,C:0,D:["Nederländerna","Tunisien"],E:["Frankrike","Senegal"],F:8,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:34},
    {name:"Pelle Lindberg",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1"],"3":["1"],"4":["X","2"],"5":["1"],"6":["1"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1"],"11":["X","2"],"12":["X","2"],"13":["X","2"]},
     answers:{A:"Alexander Isak",B:5,C:4,D:["Nederländerna","Sverige"],E:["Frankrike","Senegal"],F:7,G:"Alexander Isak",H:"Argentina"},tiebreaker:33},
    {name:"Christer Stridh",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1"],"9":["1"],"10":["1","X"],"11":["X","2"],"12":["1","2"],"13":["1"]},
     answers:{A:"Yasin Ayari",B:4,C:3,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:10,G:"Ferran Torres",H:"Spanien"},tiebreaker:44},
    {name:"Julia Strid",contact:{phone:"",email:""},
     picks:{"1":["X"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","2"],"7":["1","2"],"8":["X","2"],"9":["1"],"10":["1","2"],"11":["2"],"12":["2"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:3,C:3,D:["Nederländerna","Sverige"],E:["Frankrike","Senegal"],F:5,G:"Kylian Mbappé",H:"Spanien"},tiebreaker:13},
    {name:"Knåpen & Melle",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","2"],"8":["1","2"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","2"],"13":["2"]},
     answers:{A:"Alexander Isak",B:2,C:6,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:7,G:"Mikel Oyarzabal",H:"Spanien"},tiebreaker:41},
    {name:"Uffe Tunong",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1","2"],"3":["1"],"4":["1"],"5":["1"],"6":["2"],"7":["1"],"8":["1","2"],"9":["1"],"10":["X","2"],"11":["2"],"12":["X","2"],"13":["1","X"]},
     answers:{A:"Taha Abdi Ali",B:2,C:5,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:3,G:"Lamine Yamal",H:"Spanien"},tiebreaker:61},
    {name:"Johan Allgulander",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1","2"],"11":["2"],"12":["1","2"],"13":["X"]},
     answers:{A:"Alexander Isak",B:4,C:4,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:8,G:"VinciusJr",H:"Portugal"},tiebreaker:24},
    {name:"Sven Olof Lindgren",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1","2"],"7":["1"],"8":["1","2"],"9":["1"],"10":["1","2"],"11":["2"],"12":["1","2"],"13":["1","X"]},
     answers:{A:"Alexander Isak",B:1,C:3,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:12,G:"Cristiano Ronaldo",H:"Brasilien"},tiebreaker:62},
    {name:"Lotta Styrman",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1","2"],"9":["1"],"10":["1"],"11":["2"],"12":["X","2"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:1,C:4,D:["Sverige","Nederländerna"],E:["Frankrike","Norge"],F:5,G:"Kylian Mbappé",H:"Spanien"},tiebreaker:11},
    {name:"Simon Grunnesjö",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1"],"4":["1","X"],"5":["1"],"6":["X","2"],"7":["X","2"],"8":["1","X"],"9":["1"],"10":["1"],"11":["2"],"12":["X","2"],"13":["2"]},
     answers:{A:"Viktor Gyökeres",B:4,C:6,D:["Japan","Nederländerna"],E:["Norge","Senegal"],F:8,G:"Igor Thiago",H:"Brasilien"},tiebreaker:25},
    {name:"Frida Borin",contact:{phone:"",email:""},
     picks:{"1":["2"],"2":["1"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1"],"7":["1"],"8":["1","2"],"9":["1"],"10":["1","2"],"11":["1","2"],"12":["1","X"],"13":["1","2"]},
     answers:{A:"Anthony Elanga",B:5,C:7,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:13,G:"Kai Havertz",H:"England"},tiebreaker:43},
    {name:"Jonathan Strid",contact:{phone:"",email:""},
     picks:{"1":["2"],"2":["1"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1"],"7":["1","X"],"8":["1","X"],"9":["1"],"10":["1"],"11":["1","2"],"12":["1","2"],"13":["1","2"]},
     answers:{A:"Alexander Isak",B:6,C:6,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:12,G:"Harry Kane",H:"Frankrike"},tiebreaker:37},
    {name:"Tommie Bäcke",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","2"],"8":["1"],"9":["1"],"10":["1"],"11":["2"],"12":["1","2"],"13":["X","2"]},
     answers:{A:"Alexander Isak",B:2,C:5,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:11,G:"Harry Kane",H:"Spanien"},tiebreaker:26},
    {name:"Håkan Larsson",contact:{phone:"",email:""},
     picks:{"1":["1"],"2":["1","2"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1"],"7":["1"],"8":["1","X"],"9":["1"],"10":["1"],"11":["X","2"],"12":["1","2"],"13":["1","X"]},
     answers:{A:"Viktor Gyökeres",B:4,C:2,D:["Japan","Nederländerna"],E:["Frankrike","Senegal"],F:8,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:64},
    {name:"Niklas Ohlsson",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1","2"],"3":["1"],"4":["1"],"5":["1"],"6":["1"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1","2"],"11":["X","2"],"12":["1","2"],"13":["2"]},
     answers:{A:"Viktor Gyökeres",B:3,C:7,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:6,G:"Erling Haaland",H:"Frankrike"},tiebreaker:18},
    {name:"John Söforth",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["X"],"9":["1"],"10":["1"],"11":["X","2"],"12":["1","X"],"13":["1","2"]},
     answers:{A:"Viktor Gyökeres",B:7,C:6,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:15,G:"Harry Kane",H:"England"},tiebreaker:44},
    {name:"Pär Styrman",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1","X"],"9":["1"],"10":["1"],"11":["2"],"12":["X","2"],"13":["X","2"]},
     answers:{A:"Lucas Bergvall",B:4,C:3,D:["Japan","Sverige"],E:["Frankrike","Norge"],F:9,G:"Kylian Mbappé",H:"Spanien"},tiebreaker:21},
    {name:"Andreas Smedbakken",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1","X"],"9":["1"],"10":["1"],"11":["2"],"12":["1","X"],"13":["2"]},
     answers:{A:"Viktor Gyökeres",B:6,C:4,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:16,G:"Harry Kane",H:"Spanien"},tiebreaker:40},
    {name:"Jacob Barnholdt",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1","2"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","2"],"8":["1"],"9":["1"],"10":["1"],"11":["2"],"12":["1","X"],"13":["1","2"]},
     answers:{A:"Viktor Gyökeres",B:2,C:3,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:10,G:"Kylian Mbappé",H:"Spanien"},tiebreaker:35},
    {name:"Fredrik Norberg",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1"],"3":["1","2"],"4":["1"],"5":["1"],"6":["1","X"],"7":["X","2"],"8":["1"],"9":["1"],"10":["1","2"],"11":["2"],"12":["X","2"],"13":["2"]},
     answers:{A:"Viktor Gyökeres",B:2,C:4,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:10,G:"Kylian Mbappé",H:"Frankrike"},tiebreaker:36},
    {name:"Oscar Schilke",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1"],"13":["X","2"]},
     answers:{A:"Viktor Gyökeres",B:2,C:4,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:9,G:"Harry Kane",H:"Tyskland"},tiebreaker:26},
    {name:"Lennart Berglund",contact:{phone:"",email:""},
     picks:{"1":["1"],"2":["1"],"3":["1","X"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["X","2"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","X"],"13":["1","X"]},
     answers:{A:"Viktor Gyökeres",B:6,C:4,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:16,G:"Harry Kane",H:"Frankrike"},tiebreaker:59},
    {name:"Marcus Aittamaa",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1"],"7":["1","2"],"8":["1","X"],"9":["1"],"10":["1"],"11":["X","2"],"12":["1"],"13":["X","2"]},
     answers:{A:"Alexander Isak",B:5,C:4,D:["Japan","Nederländerna"],E:["Frankrike","Norge"],F:6,G:"Harry Kane",H:"Spanien"},tiebreaker:16},
    {name:"Tomas Näslund",contact:{phone:"",email:""},
     picks:{"1":["1","2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1"],"8":["1","X"],"9":["1"],"10":["X","2"],"11":["2"],"12":["1","2"],"13":["1"]},
     answers:{A:"Alexander Isak",B:2,C:6,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:5,G:"Erling Haaland",H:"Frankrike"},tiebreaker:18},
    {name:"Linus Näslund",contact:{phone:"",email:""},
     picks:{"1":["1","X"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["X","2"],"7":["X","2"],"8":["1","X"],"9":["1"],"10":["1","X"],"11":["1","X"],"12":["2"],"13":["2"]},
     answers:{A:"Viktor Gyökeres",B:4,C:5,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:7,G:"Didier Drogba",H:"Sverige"},tiebreaker:17},
    {name:"Jessi Barka",contact:{phone:"",email:""},
     picks:{"1":["2"],"2":["1","X"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","X"],"13":["1","2"]},
     answers:{A:"Viktor Gyökeres",B:4,C:5,D:["Nederländerna","Japan"],E:["Frankrike","Norge"],F:8,G:"Kylian Mbappé",H:"Spanien"},tiebreaker:28},
    {name:"Kalle Abrahamsson",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","2"],"8":["1","X"],"9":["1"],"10":["1","X"],"11":["2"],"12":["1","2"],"13":["2"]},
     answers:{A:"Alexander Isak",B:5,C:5,D:["Nederländerna","Sverige"],E:["Frankrike","Norge"],F:8,G:"Harry Kane",H:"England"},tiebreaker:37},
    {name:"Kristian Fantenberg",contact:{phone:"",email:""},
     picks:{"1":["X","2"],"2":["1"],"3":["1"],"4":["1"],"5":["1"],"6":["1","X"],"7":["1","X"],"8":["1"],"9":["1"],"10":["1"],"11":["X","2"],"12":["X","2"],"13":["1","2"]},
     answers:{A:"Alexander Isak",B:4,C:6,D:["Nederländerna","Japan"],E:["Frankrike","Norge"],F:9,G:"Harry Kane",H:"Frankrike"},tiebreaker:46}
  ]
};

POOL_DATA.meta.admin_password = "Admin-inloggning";

if (typeof window !== "undefined") window.POOL_DATA = POOL_DATA;
if (typeof module !== "undefined" && module.exports) module.exports = POOL_DATA;
