[
  {
    "id": 73,
    "round": "R32",
    "date": "2026-06-28",
    "time_swe": "21:00",
    "home": "Sydafrika 🇿🇦",
    "away": "Kanada 🇨🇦",
    "home_score": 0,
    "away_score": 1,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 90
  },
  {
    "id": 74,
    "round": "R32",
    "date": "2026-06-29",
    "time_swe": "19:00",
    "home": "Brasilien 🇧🇷",
    "away": "Japan 🇯🇵",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 89
  },
  {
    "id": 75,
    "round": "R32",
    "date": "2026-06-29",
    "time_swe": "22:30",
    "home": "Tyskland 🇩🇪",
    "away": "Paraguay 🇵🇾",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 90
  },
  {
    "id": 76,
    "round": "R32",
    "date": "2026-06-30",
    "time_swe": "03:00",
    "home": "Nederländerna 🇳🇱",
    "away": "Marocko 🇲🇦",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 91
  },
  {
    "id": 77,
    "round": "R32",
    "date": "2026-06-30",
    "time_swe": "19:00",
    "home": "Elfenbenskusten 🇨🇮",
    "away": "Norge 🇳🇴",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 89
  },
  {
    "id": 78,
    "round": "R32",
    "date": "2026-06-30",
    "time_swe": "23:00",
    "home": "Frankrike 🇫🇷",
    "away": "Sverige 🇸🇪",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 91
  },
  {
    "id": 79,
    "round": "R32",
    "date": "2026-07-01",
    "time_swe": "03:00",
    "home": "Mexiko 🇲🇽",
    "away": "Ecuador 🇪🇨",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 92
  },
  {
    "id": 80,
    "round": "R32",
    "date": "2026-07-01",
    "time_swe": "18:00",
    "home": "England 🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "away": "DR Kongo 🇨🇩",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 92
  },
  {
    "id": 81,
    "round": "R32",
    "date": "2026-07-01",
    "time_swe": "22:00",
    "home": "Belgien 🇧🇪",
    "away": "Senegal 🇸🇳",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 94
  },
  {
    "id": 82,
    "round": "R32",
    "date": "2026-07-02",
    "time_swe": "02:00",
    "home": "USA 🇺🇸",
    "away": "Bosnien & Hercegovina 🇧🇦",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 94
  },
  {
    "id": 83,
    "round": "R32",
    "date": "2026-07-02",
    "time_swe": "21:00",
    "home": "Spanien 🇪🇸",
    "away": "Österrike 🇦🇹",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 93
  },
  {
    "id": 84,
    "round": "R32",
    "date": "2026-07-03",
    "time_swe": "01:00",
    "home": "Portugal 🇵🇹",
    "away": "Kroatien 🇭🇷",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 93
  },
  {
    "id": 85,
    "round": "R32",
    "date": "2026-07-03",
    "time_swe": "05:00",
    "home": "Schweiz 🇨🇭",
    "away": "Algeriet 🇩🇿",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 96
  },
  {
    "id": 86,
    "round": "R32",
    "date": "2026-07-03",
    "time_swe": "20:00",
    "home": "Australien 🇦🇺",
    "away": "Egypten 🇪🇬",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 95
  },
  {
    "id": 87,
    "round": "R32",
    "date": "2026-07-04",
    "time_swe": "00:00",
    "home": "Argentina 🇦🇷",
    "away": "Kap Verde 🇨🇻",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 96
  },
  {
    "id": 88,
    "round": "R32",
    "date": "2026-07-04",
    "time_swe": "03:30",
    "home": "Colombia 🇨🇴",
    "away": "Ghana 🇬🇭",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 95
  },
  {
    "id": 89,
    "round": "R16",
    "date": "2026-07-05",
    "time_swe": "22:00",
    "home": "Vinnare Match 74",
    "away": "Vinnare Match 77",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 97
  },
  {
    "id": 90,
    "round": "R16",
    "date": "2026-07-06",
    "time_swe": "02:00",
    "home": "Kanada",
    "away": "Vinnare Match 75",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 97
  },
  {
    "id": 91,
    "round": "R16",
    "date": "2026-07-06",
    "time_swe": "21:00",
    "home": "Vinnare Match 76",
    "away": "Vinnare Match 78",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 99
  },
  {
    "id": 92,
    "round": "R16",
    "date": "2026-07-07",
    "time_swe": "02:00",
    "home": "Vinnare Match 79",
    "away": "Vinnare Match 80",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 99
  },
  {
    "id": 93,
    "round": "R16",
    "date": "2026-07-07",
    "time_swe": "18:00",
    "home": "Vinnare Match 83",
    "away": "Vinnare Match 84",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 98
  },
  {
    "id": 94,
    "round": "R16",
    "date": "2026-07-07",
    "time_swe": "22:00",
    "home": "Vinnare Match 81",
    "away": "Vinnare Match 82",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 98
  },
  {
    "id": 95,
    "round": "R16",
    "date": "2026-07-08",
    "time_swe": "18:00",
    "home": "Vinnare Match 86",
    "away": "Vinnare Match 88",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 100
  },
  {
    "id": 96,
    "round": "R16",
    "date": "2026-07-08",
    "time_swe": "22:00",
    "home": "Vinnare Match 85",
    "away": "Vinnare Match 87",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 100
  },
  {
    "id": 97,
    "round": "QF",
    "date": "2026-07-09",
    "time_swe": "22:00",
    "home": "Vinnare Match 89",
    "away": "Vinnare Match 90",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 101
  },
  {
    "id": 98,
    "round": "QF",
    "date": "2026-07-10",
    "time_swe": "21:00",
    "home": "Vinnare Match 93",
    "away": "Vinnare Match 94",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 101
  },
  {
    "id": 99,
    "round": "QF",
    "date": "2026-07-11",
    "time_swe": "23:00",
    "home": "Vinnare Match 91",
    "away": "Vinnare Match 92",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 102
  },
  {
    "id": 100,
    "round": "QF",
    "date": "2026-07-12",
    "time_swe": "03:00",
    "home": "Vinnare Match 95",
    "away": "Vinnare Match 96",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 102
  },
  {
    "id": 101,
    "round": "SF",
    "date": "2026-07-14",
    "time_swe": "21:00",
    "home": "Vinnare Match 97",
    "away": "Vinnare Match 98",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 104
  },
  {
    "id": 102,
    "round": "SF",
    "date": "2026-07-15",
    "time_swe": "21:00",
    "home": "Vinnare Match 99",
    "away": "Vinnare Match 100",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": 104
  },
  {
    "id": 103,
    "round": "Bronze",
    "date": "2026-07-18",
    "time_swe": "23:00",
    "home": "Förlorare Match 101",
    "away": "Förlorare Match 102",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": null
  },
  {
    "id": 104,
    "round": "Final",
    "date": "2026-07-19",
    "time_swe": "21:00",
    "home": "Vinnare Match 101",
    "away": "Vinnare Match 102",
    "home_score": null,
    "away_score": null,
    "extra_time": false,
    "penalty_shootout": false,
    "next_match": null
  }
]
